services:
  postgres:
    image: postgres:15
    container_name: user_db
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: