spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    drop-first: false
    change-log: classpath:db/changelog/db-changelog-master.yml
    contexts: migrated